// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.13.0
// source: nidhi/nidhi.proto

package nidhi

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var file_nidhi_nidhi_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         20429,
		Name:          "nidhi.prefix",
		Tag:           "bytes,20429,opt,name=prefix",
		Filename:      "nidhi/nidhi.proto",
	},
}

// Extension fields to descriptor.MessageOptions.
var (
	// Prefix marks this message as root object for code generation.
	//
	// optional string prefix = 20429;
	E_Prefix = &file_nidhi_nidhi_proto_extTypes[0]
)

var File_nidhi_nidhi_proto protoreflect.FileDescriptor

var file_nidhi_nidhi_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6e, 0x69, 0x64, 0x68, 0x69, 0x2f, 0x6e, 0x69, 0x64, 0x68, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6e, 0x69, 0x64, 0x68, 0x69, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3a, 0x39, 0x0a, 0x06,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xcd, 0x9f, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x72, 0x69, 0x6b, 0x72, 0x73, 0x6e, 0x61, 0x2f, 0x6e,
	0x69, 0x64, 0x68, 0x69, 0x2f, 0x6e, 0x69, 0x64, 0x68, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var file_nidhi_nidhi_proto_goTypes = []interface{}{
	(*descriptor.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
}
var file_nidhi_nidhi_proto_depIdxs = []int32{
	0, // 0: nidhi.prefix:extendee -> google.protobuf.MessageOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nidhi_nidhi_proto_init() }
func file_nidhi_nidhi_proto_init() {
	if File_nidhi_nidhi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nidhi_nidhi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_nidhi_nidhi_proto_goTypes,
		DependencyIndexes: file_nidhi_nidhi_proto_depIdxs,
		ExtensionInfos:    file_nidhi_nidhi_proto_extTypes,
	}.Build()
	File_nidhi_nidhi_proto = out.File
	file_nidhi_nidhi_proto_rawDesc = nil
	file_nidhi_nidhi_proto_goTypes = nil
	file_nidhi_nidhi_proto_depIdxs = nil
}
